env:
  global:
    - CC_TEST_REPORTER_ID=${CODE_CLIMATE_REPORTER_ID}
    - GIT_COMMITTED_AT=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then git log -1 --pretty=format:%ct; else git log -1 --skip 1 --pretty=format:%ct; fi)

language: go

go:
  - 1.8.x

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/AlekSi/gocov-xml

install:
  - go get -u gopkg.in/h2non/gock.v1
  - go get -u github.com/Microkubes/microservice-tools
  - go get -u github.com/guregu/dynamo
  - go get -u github.com/satori/go.uuid
  - go get -u github.com/goadesign/goa
  - go get -u github.com/aws/aws-sdk-go/aws
  - go get -u gopkg.in/mgo.v2

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter

script:
  - gocov test -short github.com/JormungandrK/backends/... | gocov-xml > coverage.xml && ./cc-test-reporter format-coverage -t cobertura -o coverage.json coverage.xml
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./cc-test-reporter upload-coverage -i coverage.json; fi

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    ./trigger.sh;
    fi

